services:
  taskmanager-server:
    image: node:18-alpine
    command: sh -c "npm install && npm start"
    ports:
      - "4000:4000"
    working_dir: /taskmanager-server
    volumes:
      - ./:/taskmanager-server
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:8.0
    volumes:
      - taskmanager-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  taskmanager-mysql-data: