services:
  taskmanager-server:
    image: node:18-alpine
    command: sh -c "npm install && npm run migrate && npm run start-development"
    ports:
      - "4000:4000"
      - "9229:9229"
    working_dir: /taskmanager-server
    volumes:
      - ./:/taskmanager-server

  mysql:
    image: mysql:8.0
    ports:
      - "3307:33060"
    volumes:
      - taskmanager-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  taskmanager-mysql-data: